### ISSUE TITLE
Web sanity game plan

### ISSUE THREAD

**Issue by gabek** [gabek/owncast#103]
I'm not a web developer.  I appraoched the web frontend with a set of ideals, but not so much of a technical game plan.

* I didn't want additional tooling (transpilers, bundlers).
* I wanted people to be able to open the files and make edits directly to their html, css and Javascript and have complete control over it.
* I didn't want to rely on a heavy view framework that would be a barrier of entry for people to make changes for themselves and contribute to the project.  I want people to write HTML, not learn JSX.

In general, I think these all completely stand right now.  And I've really liked that people have been able to open the project and edit it directly.

**But...**

1. While using Vue.js was a middle ground to allow for a little structure so we're not querying and manipulating the DOM directly, nobody here is a Vue expert so we end up not fully using it, or ignoring it all together.  Since Vue allowed for regular HTML but you could sprinkle additional attributes it worked for me.

1. Because we're not using a bundler we end up with spaghetti code, and we're generally discouraged from actually organizing files and splitting things into smaller components because each one will need to be added as a script tag in index.html and that's just a mess.

**This isn't scaling.**

I'd like to put together some options to move forward with to give structure to the frontend code. 

These are two separate discussions:

## **What do we want to do about the view (DOM) layer?  Stay with Vue or do something else?**

1. Get rid of Vue.  Add React without Webpack.
1. Get rid of Vue.  Add React with Webpack and start bundling.
1. Start an effort to use Vue properly since it's pretty nice, but none of us know it.

I've never done or even seen React without Webpack, so that's a huge question mark of how that works without writing unreadable files full of `React.createElement`'s.
## **What do we want to do about code organization and structure?  Do we have to start bundling in order to scale?**

1. Use ES6 modules in the browser and break things up, no longer having to add random `<script>` tags in the HTML because we can import code from modules.
2. Start using Webpack or [another bundler](https://blog.bitsrc.io/choosing-the-right-javascript-bundler-in-2020-f9b1eae0d12b).

@mattdsteele Because you're knowledgable about this stuff, I'd particularly like to hear your thoughts since you mentioned you've done entire projects with ES6 modules in the browser and it feels like that might be a nice way forward.

I have very real fears of people trying to run the project and getting NPM errors, them digging around having to learn about NVM, and troubleshooting `webpack.config`.  Also, not everyone knows React, so going all-in on non-HTML views could turn people off from at the very least contributing, but they also won't be able to customize their web page.  It's also a slippery slope to needing to bring in Redux and... oh god.

So in general, my ideals stand, **however**, if everyone thinks we should just go full on Webpack + React, then let's do it.  But let's know the pros/cons upfront.

**Comment by gabek** [comment]
I thought I'd go learn a bit about React without Webpack or Babel and found this post that's worthwhile reading.

[App with React API without tools as Webpack or Babel](https://aralroca.com/blog/app-with-react-api-without-tools-as-webpack-or-babel).
It uses Preact instead of React, but that's cool.  I'd almost prefer Preact, it's way smaller and faster and it's not made by Facebook.

Looks like it wouldn't just be `React.createElement` because you can wrap JSX (though it's not technically JSX because there's no Babel) in a `html` function.

Some other posts of interest:

* [In 2020, go bundler free](https://medium.com/@dmnsgn/in-2020-go-bundler-free-eb29c1f05fc9)
* [Using ES Modules in the Browser Today](https://www.sitepoint.com/using-es-modules/)
* [Choosing the Right JavasCript bundler in 2020](https://blog.bitsrc.io/choosing-the-right-javascript-bundler-in-2020-f9b1eae0d12b)

**Comment by mattdsteele** [comment]
Yeah, I get it.

Incidentally I wrote up a few of my thoughts last year: https://steele.blue/toolchainless/

I definitely agree that going full React + ecosystem brings a ton of drawbacks, on both the user experience and development side, so I'd steer clear of that and look for other approaches. But I think so long as you're comfortable only supporting evergreen browsers (i.e. ditching IE), you have some options for a modern development experience without buying into the whole Webkit ecosystem.

To be honest I haven't much looked at any of the code in `webroot` yet because my use case didn't require it; but after this weekend I'd be up for doing a general review to see if we can get it more structured.

So without going into specifics, here's the approaches I'd look into. All of these can be bootstrapped and run without a Webpack or other build step:

- *Continue using Vue* - You'd have to learn idiomatic Vue, but for an app this size I don't think you've outgrown it yet. I've built similar-sized apps with it without feeling too overwhelmed at least.  Some of the better developer experiences (such as [single file components](https://vuejs.org/v2/guide/single-file-components.html)) do require additional Webpack tooling, which is a bummer.

- *Preact + htm* - This gives you a React-style experience but works in a browser. htm is neat because it's a JSX-style syntax that uses vanilla JavaScript, so no build step required. You can write stuff like:

```
render({ page }) {
  return html`
    <div class="app">
      <${Header} name="ToDo's (${page})" />
      <button onClick=${() => this.addTodo()}>Add Todo</button>
      <${Footer}>footer content here<//>
    </div>
  `;
```

Example app that uses this model: https://github.com/mattdsteele/pizza-compass/tree/master/www

- *Web components (LitElement)* - I really like Web Components; they feel like the way out of the userland morass. I also [blogged about them a bit here](https://steele.blue/web-components-arent-weird-anymore/). You could write parts of the app using the Custom Elements API, or use a library like [LitElement](https://lit-element.polymer-project.org/) for a more React-like experience. Some of the really fancy stuff (like the `@property` decorator) require a build step, but it's totally usable without it.

The nice thing about all of these approaches is they don't have to take over the whole app; you could just build the chat section with a framework, and have the rest of the site be static HTML.

**Comment by gabek** [comment]
You're awesome, Matt!  Thank you for all the insights, I guess I asked the right person.

There's a handful of great options here, I'm optimistic we can find a solution.  @gingervitis is a React person, so the Preact + htm option seems like it could be a fit.  I think we'll do some experimenting with it this weekend.

Enjoy your wedding this weekend, we'll be tuning in!  Look forward to chatting more.

**Comment by gingervitis** [comment]
Yeah thank you for the insights Matt!
The Preact/HTM stuff sounds interesting, I'll have to play around with it a bit. I've been mainly concerned about overall app state management; it feels brittle the way we have it now. And yeah, I'm definitely more familiar and actually quite enjoy React development and hoping using something like that could help me feel like I've got all the pieces of the app more organized here!

**Comment by mattdsteele** [comment]
Yeah, let me know how it goes!

For state management you have a few approaches; if you like redux there are
bindings for preact: https://www.pika.dev/npm/preact-redux

There are also plenty of other approaches out there.
https://www.pika.dev/npm/unistore is another popular Flux-like option, but
if you like mobx, immer, etc go for it!

Whatever you use, check if it's available via https://www.skypack.dev/ - it
lets you link most NPM dependencies from their CDN via an `import`
statement; no Webpack required :)

**Comment by gabek** [comment]
There are people who like redux? :). Are state management libraries required?

I've never used a state management library.  The one time I built something with React I didn't use one and I still don't really get them.  Making the entire state of an application a single global object and then relying on side effects of the object changes to update the UI goes against everything I've ever believed about software development.  But then again, I'm not a web developer.  My reaction to most Javascript things are "oh god that's awful, you do that?"

**Comment by mattdsteele** [comment]
Nah; use whatever works for you. I don't like Redux much myself either, to
be honest!

That said, I've found having some sort of structure in place to help make
slices of my application's state available across components to be helpful.
As apps get bigger I find it becomes more painful to make changes to data
in one component, and have another part of the UI reflect those changes;
especially if they're in disparate parts of the component tree. It's
especially pronounced in React-y frameworks where "UI is a function of
state".

But yeah, there's more than one way to do it. The last app I built was with
[Stencil](https://stenciljs.com/) and they had a nice [state library](
https://github.com/ionic-team/stencil-store) which I haven't seen
replicated elsewhere. I also do a fair amount of Angular development, and
the approach there is to use RxJS Observables, with dependency injection.

That said, I'd love to find a simpler way to share state across components,
so I'd be curious how you did it without a library.

**Comment by graywolf336** [comment]
> As apps get bigger I find it becomes more painful to make changes to data in one component, and have another part of the UI reflect those changes; especially if they're in disparate parts of the component tree.

This is so true in many regards. For the past year I have been working with React for a web application which is essentially a CRM but for a very specific and small niche. I am personally one of those niche users/members and as a result the application has grown to be a big application with lots of features. Biggest thing I was struggling with was state management and how to get "reactivity" across several views and components of the same data without passing/fetching that data constantly.

As a result, I did switch over to Redux going all out with actions, stores, reducers, and the whole nine yards. As a side effect of doing this, I was able to implement [Server Sent Events](https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events) (SSE) and hook it up to the Redux store which then caused the application state to be reactive to an event happening on the server that was triggered by a 3rd party item (such as Stripe marking an invoice as paid or past due).

With that said, I do not think owncast is at a point where a store, such as a fully implemented Redux, would have a significant benefit; in fact it could potentially raiser the barrier of entry and reduce the amount of ease it takes to start editing/contributing to the project.

Maybe this question needs asked and answered to figure out the scope of the state management required:

What is in the "state" of the owncast web application?

**Comment by gabek** [comment]
> That said, I'd love to find a simpler way to share state across components, so I'd be curious how you did it without a library.

In short, I _mostly_ didn't.  I passed values to props.  But for a few things I did utilize [`Context`](https://reactjs.org/docs/context.html).

**Comment by gingervitis** [comment]
I suspect Redux would be a bit too heavy handed for this Owncast at this point. 
Right now I can mainly see "stream status" as the primary app state driving a couple of things throughout, but that's about it. 
The Chat section itself could definitely be its own self contained app with a couple of internal states to manage based on web socket states, but also be somewhat influenced by the stream status.  I guess I've been mainly worried as I've watched a lot of requests for features are coming in, but it's currently this vanilla JS thing that I set up (because I wasn't familiar with using Vue) and it directly manipulates the DOM , so I just feel all that could be more packaged up a bit before more features go in.

**Comment by gabek** [comment]
An update!  While I don't want to speak for @gingervitis, we did some Hello World'ing with Preact + htm + modules this weekend and I believe we're going to go forward with it.  I suggested #96 as a place we could start to get a taste of using it in the project since a standalone chat page wouldn't touch any of the existing stuff, and it could be reused when refactoring everything else into components.  But I'm optimistic!

**Comment by gingervitis** [comment]
Yeah I'll try and get a Preacty chat component set up by the end of the week and we'll see how it goes from there! 🤞

**Comment by gabek** [comment]
I've been following along with @gingervitis's updates in #96 using the approach outlined above and it looks like it's coming along really well.  This is super exciting!

**Comment by gingervitis** [comment]
Yep! I think the chat and message components are in a pretty good shape right now!

My next steps are going to be integrating them into the main app, and then clean up a whole bunch of files, and then I'll submit an MR. Hopefully in a couple days.

**Comment by gabek** [comment]
Closing this since the discussion seems to be over.  We have a plan in action!  Thank you to everyone, especially @mattdsteele and @gingervitis for pushing to make things better.
