### ISSUE TITLE
EditorConfig

### ISSUE THREAD

**Issue by graywolf336** [gabek/owncast#107]
Any thoughts regarding adding a `.editorconfig` file to help with the spacing inside javascript, css, and html files?

Golang handles the `.go` files well with it's formatting tool

**Comment by gabek** [comment]
That sounds good to me.  @gingervitis do you already have a code style you'd like us to use, or do you have an editor config you've been using locally?

**Comment by mojo706** [comment]
Wouldn't something like `prettier` work in this case or do you wanna limit the number of packages to be installed?

**Comment by gingervitis** [comment]
Ooh yeah I've been wondering about code style as well and considered adding some sort of linter. But I've haven't really made any moves to do anything about it yet, not even locally! I'd be option to using whatever editor config people want to add. Preferably package free.

**Comment by gingervitis** [comment]
Ok I just pushed up a starter `.editorconfig` file to `master`.  I'm generally indifferent to most of the properties, so if anyone has any strong opinions about them, feel free to edit the file!

Though I'm not sure if this file is working? I can't tell what it's doing in my VScode. I installed the plugin, but I still see no changes. @graywolf336 since you mentioned it, do you happen to use VScode and know how to get it to work?

**Comment by graywolf336** [comment]
@gingervitis yes, you will have to install the extension for it to respect the config file: https://marketplace.visualstudio.com/items?itemName=EditorConfig.EditorConfig

Although, having a linter in addition to this might help some, just not sure when the best time to lint it would be.

**Comment by mojo706** [comment]
Best time to lint IMHO is just before commiting/pushing. That way you make sure the repo has the style you need.

**Comment by gabek** [comment]
`.editorconfig` was added by ginger, but feel free to make any changes to it or explore the formatting conversation!
