### ISSUE TITLE
CORS preflight requests fail when Cache-Control header is set (DigitalOcean Spaces)

### ISSUE THREAD

**Issue by mattdsteele** [gabek/owncast#117]
Related to the issue I mentioned at https://github.com/gabek/owncast/issues/52#issuecomment-674559612

When investigating the differences between the Owncast player and the player on my website, I noticed I don't have this code (from player.js):

```
    videojs.Hls.xhr.beforeRequest = function (options) {
      const cachebuster = Math.round(new Date().getTime() / 1000);
      options.uri = options.uri + "?omgwtf=" + cachebuster;
      options.headers = {
        'Cache-Control':'no-cache'
      };
      return options;
    };
```

When I added this in to my website (more speciically, setting `options.headers`), it began to fail.

Looking through Dev Tools, I notice the [CORS preflight request](https://developer.mozilla.org/en-US/docs/Glossary/preflight_request) includes this header:

```
Access-Control-Request-Headers: cache-control
```

Which results in a 403 Forbidden when trying to pull the files from the Spaces bucket. Similarly, if I remove the headers from the Owncast UI, it works fine.

In the Spaces configuration, there's an option to set "Allowed Headers". When I add in "Cache-Control", it works fine:

![image](https://user-images.githubusercontent.com/389077/90708029-7c64b780-e25e-11ea-95cf-135f4e598e4f.png)

So! I see two approaches we could take:

1. Document that some S3-compatible providers will require you to add this header to their HTTP configuration
2. Remove the `options.headers` from the `beforeRequest` check

I'm cool putting in a PR for either, but I'd lean toward option 2; mainly because I'm not sure setting the headers is even necessary; given the cache-busting query param we're adding. WDYT?

**Comment by gabek** [comment]
This is a great find, thanks for looking into it Matt!

I'm double dipping a bit on the cache busting. I was seeing a scenario where the stream was offline, and then would come online, but the player would play the previously offline content instead of fetching the new playlist so I heavy handedly forced it to do so.  Obviously the cache headers are the official way to handle it, and is much cleaner than throwing arbitrary query params to every request.  But now we have this new header issue.

It's pretty odd, you'd think the storage provider would just ignore any headers it doesn't understand instead of throwing errors.

I guess it makes sense to stick with the cache busting query params and remove the cache control header if it's going to cause issues.  Thanks again!

**Comment by gabek** [comment]
Also, feel free to change the param from `omgwtf` to something a little more reasonable :)
