### ISSUE TITLE
Docker build: Go-SQLite3 requires cgo to work

### ISSUE THREAD

**Issue by jeyemwey** [gabek/owncast#60]
Hi, thanks for this awesome project. I was following the [QuickStart guide](https://github.com/gabek/owncast/blob/master/doc/quickstart.md#through-docker) for Docker. While building the container worked, I was unable to start it:

```
$ docker run -p 8080:8080 -p 1935:1935 -it owncast
FATA[0000] Binary was compiled with 'CGO_ENABLED=0', go-sqlite3 requires cgo to work. This is a stub
```

I'm sure that the `CGO_ENABLED=0` is in the Dockerfile for a reason, however the programm does not seem to start?

I'm using Docker for Windows through Hyper-V, in case this is an issue?

**Comment by gabek** [comment]
Good catch!  It's in the Dockerfile because cgo used to not be required, and now it is and I never updated and tested it. Whoops! 😃  
It also requires gcc now ([discussed here](https://github.com/gabek/owncast/issues/52#issuecomment-657266397)), so I'll get these changes into the Dockerfile.  
Let me fix this, test it, and get back to you.  Thanks for letting me know!

**Comment by gabek** [comment]
Alright, updated!  I also used this as an opportunity to create some Github actions to spin up the Docker container to make sure these regressions don't happen again.  I'll probably have to make some tweaks to the jobs to dial them in, but it's building and running now.

**Comment by jeyemwey** [comment]
Great, thanks for the quick fix!
