### ISSUE TITLE
Different S3 serving endpoint (e.g. CDN support)

### ISSUE THREAD

**Issue by mattdsteele** [gabek/owncast#90]
DigitalOcean supports a [built-in CDN](https://www.digitalocean.com/docs/spaces/how-to/enable-cdn/) when using their S3-compatible Spaces storage. After enabling, use of the CDN just requires changing the endpoint; e.g.:

* Origin: https://bucket.region.digitaloceanspaces.com
* Edge: https://bucket.region.cdn.digitaloceanspaces.com

It's also possible to configure a custom domain (using a subdomain you own, for example).

I can try to add a new configuration parameter to support this (something like `s3.servingHostname`), but wanted to get your thoughts before making the change.

Simplest approach would be to just generate and return the custom URL within `s3Storage.Save`, but if you think there's value in pulling this up more generally, we could probably move it into `monitor.go`. This would potentially let other storage providers use the same param. I don't think this would be valuable for local serving, but maybe for other providers in the future? I dunno.

**Comment by gabek** [comment]
AWS also offers a feature to change the host to get a CDN'ized version of it, not to mention just having control over where the video segments are in general would be useful across the board.

So as it stands the `Segment` type (in `playlist.go`) knows the relative path (via `
RelativeUploadPath` like `1/stream-1595834191.ts`) and the absolute remote URL (`RemoteID`, not a great name, `https://gabevideo.us-east-1.linodeobjects.com/gabevideo/hls/0/stream-1595814948.ts`)

So in `GenerateRemotePlaylist` it seems like instead of using just the `RemoteID` if the config has a `servingHostname` it could instead piece together its own absolute URL using the overriden host in the config + the relative path.  And then if an overridden host doesn't exist in the config then `GenerateRemotePlaylist` would just do what it already does now and use the `RemoteID`.

I think? :)

If you want to take a stab at this, go for it!  Otherwise I can probably get to it this week.

**Comment by gabek** [comment]
Just noticed you already looked at it!  So the only thought I had that's different is instead of rewriting the URL in `Save` we rewrite it in `GenerateRemotePlaylist`, only because that URL returned from save is technically correct, but we just want to reference it differently in the playlist.

**Comment by mattdsteele** [comment]
Yup, I was just mucking around to see if I could get something working. I'll update the branch and open a PR
